# Generated by Django 4.2.7 on 2024-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('imperial', models.CharField(max_length=10)),
                ('metric', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
