# Generated by Django 4.2.7 on 2024-02-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnaceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=50)),
                ('furnace_no', models.CharField(max_length=50, unique=True)),
                ('furnace_description', models.CharField(max_length=500)),
                ('iron_losses', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('joule_losses_coeffient', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('default_epi_index', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('corrected_reactance_coefficient', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('design_mv', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('silicon_fc', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('k_sic', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('shell_losses', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('default_moisture', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('created_by', models.IntegerField()),
                ('record_status', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_ai', to='utils.master')),
                ('electrode_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_electrode_type', to='utils.master')),
                ('lime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_lime', to='utils.master')),
                ('power_delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_power_delivery', to='utils.master')),
                ('remelt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_remelt', to='utils.master')),
                ('sand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_sand', to='utils.master')),
                ('silica_fume_default_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_smdm', to='utils.master')),
                ('skull', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_skull', to='utils.master')),
                ('slag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_slag', to='utils.master')),
                ('slag_product_default_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_spdm', to='utils.master')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_furnace_workshop', to='plant.plantconfigworkshop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FurnaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.IntegerField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('created_by', models.IntegerField()),
                ('record_status', models.BooleanField(default=True)),
                ('furnace_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_config_products', to='furnace.furnaceconfig')),
                ('product_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_furnace_product_state', to='utils.master')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_furnace_product_type', to='utils.master')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FurnaceElectrode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.IntegerField(blank=True, null=True)),
                ('electrode_type_id', models.IntegerField(null=True)),
                ('type_name', models.CharField(max_length=50)),
                ('core_mass_length', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('paste_mass_length', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('casing_mass_length', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('created_by', models.IntegerField()),
                ('record_status', models.BooleanField(default=True)),
                ('casing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_electrode_casing', to='utils.master')),
                ('core', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_furnace_electrode', to='utils.master')),
                ('furnace_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_config_electrodes', to='furnace.furnaceconfig')),
                ('paste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_electrode_paste', to='utils.master')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FurnaceConfigStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.CharField(max_length=10)),
                ('order', models.SmallIntegerField()),
                ('record_status', models.BooleanField(default=True)),
                ('furnace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnace_config_step', to='furnace.furnaceconfig')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='ControlParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('param', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('record_status', models.BooleanField(default=True)),
                ('furnace_config_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_control_params', to='furnace.furnaceconfigstep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('record_status', models.BooleanField(default=True)),
                ('furnace_config_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_additives', to='furnace.furnaceconfigstep')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
