# Generated by Django 4.2.7 on 2024-02-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_status', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=100, verbose_name='master_category')),
                ('value', models.CharField(max_length=100, verbose_name='value')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_status', models.BooleanField(default=True)),
                ('module_name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('function_name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('record_status', models.BooleanField(default=True)),
                ('module', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='module_functions', to='utils.module')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
