# Generated by Django 5.0.1 on 2024-01-24 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ERP')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FurnaceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=50)),
                ('furnace_no', models.CharField(max_length=50)),
                ('furnace_description', models.CharField(max_length=500)),
                ('power_delivery_id', models.IntegerField()),
                ('electrode_type_id', models.IntegerField()),
                ('iron_losses', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('joule_losses_coeffient', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('default_epi_index', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('corrected_reactance_coefficient', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('design_mv', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('silica_fume_default_material', models.IntegerField(null=True)),
                ('slag_product_default_material', models.IntegerField(null=True)),
                ('silicon_fc', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('k_sic', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('shell_losses', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('default_moisture', models.BooleanField(default=False)),
                ('remelt', models.IntegerField(null=True)),
                ('sand', models.IntegerField(null=True)),
                ('ai', models.IntegerField(null=True)),
                ('lime', models.IntegerField(null=True)),
                ('slag', models.IntegerField(null=True)),
                ('skull', models.IntegerField(null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('created_by', models.IntegerField()),
                ('record_status', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='master_category')),
                ('value', models.CharField(max_length=100, verbose_name='value')),
                ('description', models.TextField()),
                ('recordStatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('created_by', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('plant_name', models.CharField(max_length=100, verbose_name='plant_config_name')),
                ('area_code', models.CharField(max_length=100, verbose_name='plant_config_area_code')),
                ('plant_address', models.CharField(max_length=100, verbose_name='plant_config_address')),
                ('timezone_id', models.IntegerField(verbose_name='plant_config_language')),
                ('language_id', models.IntegerField()),
                ('unit_id', models.IntegerField()),
                ('currency_id', models.IntegerField()),
                ('shift1_from', models.CharField(max_length=100, verbose_name='plant_config_shift1_from')),
                ('shift1_to', models.CharField(max_length=100, verbose_name='plant_config_shift1_to')),
                ('shift2_from', models.CharField(max_length=100, verbose_name='plant_config_shift2_from')),
                ('shift2_to', models.CharField(max_length=100, verbose_name='plant_config_shift2_to')),
                ('shift3_from', models.CharField(max_length=100, verbose_name='plant_config_shift3_from')),
                ('shift3_to', models.CharField(max_length=100, verbose_name='plant_config_shift3_to')),
                ('created_by', models.CharField(max_length=100, verbose_name='plant_config_created_by')),
                ('modified_by', models.CharField(max_length=100, verbose_name='plant_config_modified_by')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('record_status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(default=0)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FurnaceConfigStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=10)),
                ('order', models.SmallIntegerField()),
                ('furnace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnace_config_step', to='app.furnaceconfig')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='ControlParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('furnace_config_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_control_params', to='app.furnaceconfigstep')),
            ],
        ),
        migrations.CreateModel(
            name='Additives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('furnace_config_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_additives', to='app.furnaceconfigstep')),
            ],
        ),
        migrations.CreateModel(
            name='FurnaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_state', models.IntegerField(null=True)),
                ('product_type', models.IntegerField(null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('created_by', models.IntegerField()),
                ('record_status', models.BooleanField(default=True)),
                ('furnace_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_config_products', to='app.furnaceconfig')),
            ],
        ),
        migrations.CreateModel(
            name='FurnaceElectrode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electrode_type_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=50)),
                ('core_mass_length', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('paste_id', models.IntegerField(null=True)),
                ('paste_mass_length', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('casing_id', models.IntegerField(null=True)),
                ('casing_mass_length', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('created_by', models.IntegerField()),
                ('record_status', models.BooleanField(default=True)),
                ('furnace_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_config_electrodes', to='app.furnaceconfig')),
                ('core_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_furnace_electrode', to='app.master')),
            ],
        ),
        migrations.CreateModel(
            name='PlantConfigProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('plant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_config_products', to='app.plantconfig')),
            ],
            options={
                'db_table': 'plant_config_product',
            },
        ),
        migrations.CreateModel(
            name='PlantConfigWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_id', models.IntegerField()),
                ('workshop_name', models.CharField(max_length=500)),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('plant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_config_workshops', to='app.plantconfig')),
            ],
            options={
                'db_table': 'plant_config_workshop',
            },
        ),
        migrations.AddField(
            model_name='furnaceconfig',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_furnace_workshop', to='app.plantconfigworkshop'),
        ),
        migrations.CreateModel(
            name='PlantConfigFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.IntegerField()),
                ('function_id', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_config_function', to='app.plantconfig')),
            ],
            options={
                'unique_together': {('module_id', 'function_id')},
            },
        ),
    ]
