# Generated by Django 5.0.1 on 2024-01-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='area',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
