# Generated by Django 5.0.1 on 2024-01-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furnaceelectrode',
            old_name='core_id',
            new_name='master',
        ),
    ]
