# Generated by Django 5.0.1 on 2024-01-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_core_id_furnaceelectrode_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnaceproduct',
            name='product_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_furnace_product_state', to='app.master'),
        ),
        migrations.AlterField(
            model_name='furnaceproduct',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_furnace_product_type', to='app.master'),
        ),
    ]
