# Generated by Django 4.2.9 on 2024-01-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plant_area_plant_code_alter_plant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='area',
            new_name='area_code',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='code',
            new_name='plant_id',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='name',
            new_name='plant_name',
        ),
    ]
