# Generated by Django 5.0.1 on 2024-01-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_furnaceproduct_product_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnaceconfig',
            name='power_delivery_id',
        ),
        migrations.AddField(
            model_name='furnaceconfig',
            name='power_delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_power_delivery', to='app.master'),
        ),
    ]
