# Generated by Django 5.0.1 on 2024-01-24 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_furnaceconfig_power_delivery_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnaceconfig',
            name='electrode_type_id',
        ),
        migrations.AddField(
            model_name='furnaceconfig',
            name='electrode_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_electrode_type', to='app.master'),
        ),
        migrations.AlterField(
            model_name='furnaceconfig',
            name='ai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_ai', to='app.master'),
        ),
        migrations.AlterField(
            model_name='furnaceconfig',
            name='lime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_lime', to='app.master'),
        ),
        migrations.AlterField(
            model_name='furnaceconfig',
            name='remelt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_remelt', to='app.master'),
        ),
        migrations.AlterField(
            model_name='furnaceconfig',
            name='sand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_sand', to='app.master'),
        ),
        migrations.AlterField(
            model_name='furnaceconfig',
            name='silica_fume_default_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_smdm', to='app.master'),
        ),
        migrations.AlterField(
            model_name='furnaceconfig',
            name='skull',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_skull', to='app.master'),
        ),
        migrations.AlterField(
            model_name='furnaceconfig',
            name='slag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_slag', to='app.master'),
        ),
        migrations.AlterField(
            model_name='furnaceconfig',
            name='slag_product_default_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furnace_master_spdm', to='app.master'),
        ),
    ]
