# Generated by Django 5.0.1 on 2024-01-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_furnaceconfig_electrode_type_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnaceelectrode',
            name='casing_id',
        ),
        migrations.RemoveField(
            model_name='furnaceelectrode',
            name='paste_id',
        ),
        migrations.AddField(
            model_name='furnaceelectrode',
            name='casing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_electrode_casing', to='app.master'),
        ),
        migrations.AddField(
            model_name='furnaceelectrode',
            name='paste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_electrode_paste', to='app.master'),
        ),
    ]
