# Generated by Django 5.0.1 on 2024-01-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_furnaceelectrode_casing_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furnaceelectrode',
            old_name='master',
            new_name='core',
        ),
        migrations.AlterField(
            model_name='furnaceelectrode',
            name='electrode_type_id',
            field=models.IntegerField(null=True),
        ),
    ]
