# Generated by Django 4.2.7 on 2024-01-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_design_mw_furnaceconfig_design_mv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('created_by', models.IntegerField()),
                ('module_name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('record_status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='furnaceconfig',
            name='furnace_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='furnaceelectrode',
            name='casing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_electrode_casing', to='app.master'),
        ),
        migrations.AlterField(
            model_name='furnaceelectrode',
            name='core',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_furnace_electrode', to='app.master'),
        ),
        migrations.AlterField(
            model_name='furnaceelectrode',
            name='paste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_electrode_paste', to='app.master'),
        ),
        migrations.AlterField(
            model_name='furnaceproduct',
            name='product_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_furnace_product_state', to='app.master'),
        ),
        migrations.AlterField(
            model_name='furnaceproduct',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_furnace_product_type', to='app.master'),
        ),
        migrations.AlterField(
            model_name='plantconfigworkshop',
            name='workshop_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='FunctionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('created_by', models.IntegerField()),
                ('function_name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('record_status', models.BooleanField(default=True)),
                ('module', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='module_functions', to='app.modulemaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
