# Generated by Django 5.0.1 on 2024-01-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_modulemaster_alter_furnaceconfig_furnace_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantconfigfunction',
            name='record_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plantconfigproduct',
            name='record_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plantconfigworkshop',
            name='record_status',
            field=models.BooleanField(default=True),
        ),
    ]
