# Generated by Django 5.0.1 on 2024-01-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_plantconfigfunction_record_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionmaster',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='functionmaster',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='modulemaster',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='modulemaster',
            name='modified_by',
        ),
    ]
