# Generated by Django 5.0.1 on 2024-01-27 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='create',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_permissions', to='accounts.function'),
        ),
        migrations.DeleteModel(
            name='PlantUser',
        ),
    ]
