# Generated by Django 4.2.7 on 2024-01-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rolepermission_view_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=255, verbose_name='Name of Role'),
        ),
    ]
