# Generated by Django 5.0.1 on 2024-01-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='plant_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(related_name='user_roles', to='accounts.role'),
        ),
    ]
