# Generated by Django 5.0.1 on 2024-01-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_rolepermission_plant_id_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='function',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='module',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='module',
            name='modified_by',
        ),
    ]
