# Generated by Django 5.0.1 on 2024-01-27 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_function_created_by_and_more'),
        ('app', '0013_remove_functionmaster_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='function',
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='function_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function_permissions', to='app.functionmaster'),
        ),
    ]
