# Generated by Django 5.0.1 on 2024-01-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='is_active',
            new_name='is_delete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('sso', 'SSO'), ('simple', 'Simple')], max_length=50),
        ),
    ]
