# Generated by Django 4.2.7 on 2024-01-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_is_active_role_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
