# Generated by Django 4.2.7 on 2024-01-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
