# Generated by Django 5.0.1 on 2024-01-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_role_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
