# Generated by Django 4.2.7 on 2024-02-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ERP')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_status', models.BooleanField(default=True)),
                ('plant_name', models.CharField(default='', max_length=100)),
                ('plant_id', models.CharField(default='', max_length=20)),
                ('area_code', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_status', models.BooleanField(default=True)),
                ('plant_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('plant_name', models.CharField(max_length=100, verbose_name='plant_config_name')),
                ('area_code', models.CharField(max_length=100, verbose_name='plant_config_area_code')),
                ('plant_address', models.CharField(max_length=100, verbose_name='plant_config_address')),
                ('timezone_id', models.IntegerField(verbose_name='plant_config_language')),
                ('language_id', models.IntegerField()),
                ('unit_id', models.IntegerField()),
                ('currency_id', models.IntegerField()),
                ('shift1_from', models.CharField(max_length=100, verbose_name='plant_config_shift1_from')),
                ('shift1_to', models.CharField(max_length=100, verbose_name='plant_config_shift1_to')),
                ('shift2_from', models.CharField(max_length=100, verbose_name='plant_config_shift2_from')),
                ('shift2_to', models.CharField(max_length=100, verbose_name='plant_config_shift2_to')),
                ('shift3_from', models.CharField(max_length=100, verbose_name='plant_config_shift3_from')),
                ('shift3_to', models.CharField(max_length=100, verbose_name='plant_config_shift3_to')),
                ('created_by', models.CharField(max_length=100, verbose_name='plant_config_created_by')),
                ('modified_by', models.CharField(max_length=100, verbose_name='plant_config_modified_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('record_status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(default=0)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlantConfigWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.IntegerField(blank=True, null=True)),
                ('workshop_id', models.IntegerField(unique=True)),
                ('workshop_name', models.CharField(max_length=500)),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('record_status', models.BooleanField(default=True)),
                ('plant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_config_workshops', to='plant.plantconfig')),
            ],
            options={
                'db_table': 'plant_config_workshop',
            },
        ),
        migrations.CreateModel(
            name='PlantConfigProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.IntegerField(blank=True, null=True)),
                ('product_id', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('record_status', models.BooleanField(default=True)),
                ('plant_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_config_products', to='plant.plantconfig')),
            ],
            options={
                'db_table': 'plant_config_product',
            },
        ),
        migrations.CreateModel(
            name='PlantConfigFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_by', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_status', models.BooleanField(default=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_config_functions', to='utils.function')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_config_modules', to='utils.module')),
                ('plant_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_config_function', to='plant.plantconfig')),
            ],
            options={
                'unique_together': {('module', 'function')},
            },
        ),
    ]
