# Generated by Django 4.2.7 on 2024-02-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantconfigfunction',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_functions', to='utils.function'),
        ),
    ]
